### ISSUE TITLE
Whatsapp not display properly, unusable.

### ISSUE THREAD

**Issue by yataghan012** [ivan-hc/WhatsApp-nativefier-appimage#1]
Hello, during the last week I could barely use anything on this appimage. Like shown on the screenshot below. I updated the appimage but it's still the same. Sometimes it shows only the background colors of whatsapp web and nothing more, it seems to be strictly a problem displaying the site properly, because I do receive messages. 
I also used to get a message saying that my browser was not updated, I don't exactly remember, I can't read it anymore.

I'm on Manjaro xfce, updated. Latest LTS Linux kernel.
![Captura de pantalla_2024-08-05_09-33-50](https://github.com/user-attachments/assets/71d50b15-7b6b-4b21-a070-8f249f0095bc)

**Comment by ivan-hc** [comment]
hi, I've just noticed that I forgot to add sources:
- https://aur.archlinux.org/packages/whatsapp-nativefier
- https://github.com/frealgagu/archlinux.whatsapp-nativefier

have you got the same issue with the AUR package?

If yes, you should inform the developer.

**Comment by ivan-hc** [comment]
it seems that nativefier is unmaintained since 2023, I've just read some comments in the AUR page

**Comment by yataghan012** [comment]
> it seems that nativefier is unmaintained since 2023, I've just read some comments in the AUR page

It didn't fix it, and I prefer portable AppImages. Any other whatsapp appimage that you suggest??

**Comment by ivan-hc** [comment]
> Any other whatsapp appimage that you suggest??

From my package manager "AM" https://github.com/ivan-hc/AM

![Istantanea_2024-08-05_16-58-06](https://github.com/user-attachments/assets/51c9b26f-c096-40fa-a7dd-389e691ec38b)

**Comment by ivan-hc** [comment]
@yataghan012 alternatively, can you test one of the artifacts here?

https://github.com/ivan-hc/WhatsApp-nativefier-appimage/actions/workflows/CI.yml

maybe I should stop updating this AppImage and keep one version. I don't know. I think its better waiting the developer to fix the issue.

**Comment by yataghan012** [comment]
> > Any other whatsapp appimage that you suggest??
> 
> From my package manager "AM" https://github.com/ivan-hc/AM
> 
> ![Istantanea_2024-08-05_16-58-06](https://private-user-images.githubusercontent.com/88724353/355149347-51c9b26f-c096-40fa-a7dd-389e691ec38b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NzAyNDgsIm5iZiI6MTcyMjg2OTk0OCwicGF0aCI6Ii84ODcyNDM1My8zNTUxNDkzNDctNTFjOWIyNmYtYzA5Ni00MGZhLWE3ZGQtMzg5ZTY5MWVjMzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE0NTkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NGExZGNhOTY1NGYwYzBkZWU5MjNkNmUzMDVjM2E1MDIwMjE5ZGQ0ZmMxZmM3NWJjOTE0OGUzZmQxMzdhODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tIIV3r5Edgdu7bhBHTsYk0By6inZUZNFDmp1Hgyogkg)

great. Thanks a lot, Altus is perfect. ;)

**Comment by yataghan012** [comment]
> @yataghan012 alternatively, can you test one of the artifacts here?
> 
> https://github.com/ivan-hc/WhatsApp-nativefier-appimage/actions/workflows/CI.yml
> 
> maybe I should stop updating this AppImage and keep one version. I don't know. I think its better waiting the developer to fix the issue.

I tested the latest one, same thing. The image is buggy and changes colors when I hover the mouse on.

**Comment by ivan-hc** [comment]
what about the one of 1-2-3 months ago?

**Comment by ivan-hc** [comment]
if you click on a workflow, in the footer of the page you can find a package to download

**Comment by yataghan012** [comment]
> if you click on a workflow, in the footer of the page you can find a package to download

yes, I'm doing that. One that's three months old also breaks, but shows:
![Captura de pantalla_2024-08-05_12-19-19](https://github.com/user-attachments/assets/1e5e9597-aca8-4ba5-bbaa-813ae9dc3344)

**Comment by ivan-hc** [comment]
OK, now its clear.

Since Nativefier is no more maintained, the Electron build or Chrome/Chromium version it uses have old APIs, and Google have changed these APIs a lot of times.

In brief, old builds of Chrome are not compatible with modern APIs.

This should affect all old Electron apps that still use online services, such as WhatsApp Web.

Personally, I use Firefox for WhatsApp Web. You instead should rely on a modern client.

I've listed all the ones available in the repo of my package manager "AM", and I've already tested some in the past:
- Altus is good;
- Walc is good too, but you need to create a .home directory wih the same name of the AppImage to prevent prompting the creation of its own launcher (see https://github.com/ivan-hc/AM#stop-appimage-prompt-to-create-its-own-launcher-desktop-integration-and-doubled-launchers);
- whatsapp-for-linux should be more similar to an official client;
- zapzap is pretty popular, I remember of it was already available more than 10 years ago, before whatsapp web was launched.

So I suggest to change client. I'm sorry I can't fix my AppImage. You know, it depends on another upstream package, so the issue is there.

Thanks for let me know about this.

Is this solves at least your doubt, please close this issue.

As a maintainer, I must wait the upstream developer that fixes this issue.

**Comment by yataghan012** [comment]
no problem, there are plenty of other appimages.
